// crosswordData.js
const crosswordData = {
  animal: [
    [
        {
            answer: "TIGER",
            hint: "The powerful predator roams the jungle",
            startx: 4,
            starty: 2,
            orientation: "down",
            position: 3,
        },
        {
            answer: "EAGLE",
            hint: "A majestic bird known for its keen eyesight",
            startx: 4,
            starty: 5,
            orientation: "across",
            position: 1,
        },
        {
            answer: "GORILLA",
            hint: "A powerfully built great ape with a large head and short neck",
            startx: 1,
            starty: 3,
            orientation: "across",
            position: 2,
        },
        {
            answer: "WOLF",
            hint: "A wild carnivorous mammal that live and hunt in packs",
            startx: 2,
            starty: 2,
            orientation: "down",
            position: 4,
        },
        // Add more animal-themed crossword data as needed
    ],
    [
        {
            answer: "LION",
            hint: "The king of the jungle",
            startx: 3,
            starty: 1,
            orientation: "down",
            position: 3,
        },
        {
            answer: "LEOPARD",
            hint: "An animal with brown coat and black spots",
            startx: 1,
            starty: 3,
            orientation: "across",
            position: 1,
        },
        {
            answer: "PANDA",
            hint: "A large bearlike mammal with characteristic black and white markings",
            startx: 5,
            starty: 2,
            orientation: "down",
            position: 4,
        },
        {
            answer: "SNAKE",
            hint: "A long limbless reptile",
            startx: 3,
            starty: 6,
            orientation: "across",
            position: 2,
        },
    ],
  ],
  cafe: [
    [
        {
            answer: "LATTE",
            hint: "A drink of Italian origin made with espresso and steamed milk",
            startx: 3,
            starty: 1,
            orientation: "down",
            position: 3,
        },
        {
            answer: "MATCHA",
            hint: "A finely ground powder of specially grown and processed green tea leaves",
            startx: 1,
            starty: 3,
            orientation: "across",
            position: 1,
        },
        {
            answer: "WAFFLE",
            hint: "A small crisp batter cake, eaten hot with butter or syrup",
            startx: 6,
            starty: 2,
            orientation: "down",
            position: 4,
        },
        {
            answer: "CAKES",
            hint: "A baked item of soft sweet food made from a mixture of flour, fat, eggs, sugar, and other ingredients",
            startx: 3,
            starty: 7,
            orientation: "across",
            position: 2,
        },
       
    ],
    [
        {
            answer: "BROWNIES",
            hint: "A chocolate baked confection, may be either fudgy or cakey",
            startx: 1,
            starty: 6,
            orientation: "across",
            position: 2,
        },
        {
            answer: "MUFFIN",
            hint: "A small domed spongy cake made with eggs and baking powder",
            startx: 6,
            starty: 2,
            orientation: "down",
            position: 2,
        },
        {
            answer: "CARAMEL",
            hint: "A small domed spongy cake made with eggs and baking powder",
            startx: 2,
            starty: 2,
            orientation: "across",
            position: 2,
        },
    ],
  ],
  instrument: [
    [
        {
            answer: "FLUTE",
            hint: "A musical instrument with a high-pitched sound",
            startx: 1,
            starty: 4,
            orientation: "across",
            position: 1,
        },
        {
            answer: "DRUM",
            hint: "A percussion instrument sounded by being struck with sticks or the hands",
            startx: 3,
            starty: 2,
            orientation: "down",
            position: 3,
        },
        {
            answer: "CELLO",
            hint: "A bass instrument of the violin family",
            startx: 5,
            starty: 3,
            orientation: "down",
            position: 4,
        },
        {
            answer: "VIOLIN",
            hint: "A stringed musical instrument of treble pitch, played with a horsehair bow",
            startx: 3,
            starty: 7,
            orientation: "across",
            position: 2,
        },
       
    ],
    [
        {
            answer: "GUITAR",
            hint: "A musical instrument, usually made of wood, with six strings and a long neck, played with the fingers or a plectrum",
            startx: 2,
            starty: 5,
            orientation: "across",
            position: 1,
        },
        {
            answer: "CYMBALS",
            hint: "A flat, round musical instrument made of brass that makes a loud noise when hit with a stick or struck against another one",
            startx: 6,
            starty: 1,
            orientation: "down",
            position: 4,
        },
        {
            answer: "LYRE",
            hint: "A stringed instrument like a small U-shaped harp with strings fixed to a crossbar",
            startx: 5,
            starty: 2,
            orientation: "across",
            position: 2,
        },
        {
            answer: "CHIME",
            hint: "A bell or a metal bar or tube that is tuned and used in a set to produce a melodious series of ringing sounds when struck",
            startx: 4,
            starty: 3,
            orientation: "down",
            position: 3,
        },
    ],
  ],
};

export default crosswordData;